### ISSUE TITLE
Notification Deeplink doesn't trigger onDeeplink listener for Android

### ISSUE THREAD

**Issue by KaterynaPotrusRedge** [Synerise/react-native-synerise-sdk#5]
Good evening! 
I have faced an issue, that for iOS devices and Android devices deeplinks work different. I expected such a thing, but I didn't know that listeners will not work for the Android side.
Deeplinks for Android work for me in case if I have linking props in NavigationContainer and I don't have a trigger of the Injector's listener "onDeeplink". For iOS listeners work just fine
Is it expected work for these platforms or could I ask for some sort of advices how to fix it?

**Comment by konned** [comment]
Hi, 
In android onDeepLink is called only when you trigger deepLink inside banner or walkthrough. What you have written above is expected work for these platforms.

**Comment by KaterynaPotrusRedge** [comment]
PK, thank you very much for the answer!
